linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gocritic
    - revive
    - misspell
    - prealloc

linters-settings:
  errcheck:
    exclude-functions:
      - (io.Closer).Close
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: error-return
      - name: error-strings
      - name: exported
      - name: increment-decrement
      - name: var-naming

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
